# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

name: AzureARMDeploy

jobs:

    deploy:
      runs-on: ubuntu-latest
      steps:

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploying
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create \
            --name StorageAccountDeployment \
            --resource-group savdevgithubdeploy \
            --template-file armtemplates/storageaccount.json \
            --parameters storageAccountType=Standard_GRS
